---
title: "Data Exploration"
author: "Group 4"
date: "7/6/2023"
format: pdf
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

# Exploring the Data
Answer the following questions:

What is your outcome variable(s)? How well does it measure the outcome you are 
interested in? How does it relate to your hypotheses? What are your key 
explanatory variables? In addition, create a table of summary statistics for 
the variables you are planning to use.

General Answer: Our dependent variable is civil society participation. We will 
use the predictor variables listed above, which include: civil society repression effort scores, social support scores, freedom to make life choices, presence of 
war, presence of coups, participation rate in civil society, generosity, 
education, and government corruption. 

## Merging data - James
```{r load-data}

load("/cloud/project/data/vdemdata-master/data/vdem.RData")

# Merge data by country and year/time

```

## Cleaning data - Alicia 
- Count how many NA observations we have. If it is under %, we will omit the obs.
or we could assign some values to them using given method.
- Deal with country name changes - optional
- Drop obs or columns not needed 

- Histograms and box plots 
- Create a table of summary statistics for the variables you are planning to use.

## Code book - README.qmd - Kaori
- Location must be specified

## Data Visualization - Ephrata and Kaori 
Question 1:  
How well does it measure the outcome you are interested in? - Kaori

Question 2: 
What is our hypothesis? - Kaori 
How do our variable choices relate to our hypotheses? (paraphrasing from the proposal) - Kaori 

Visualization group 1: 
- A correlation heat map - Kaori 

Visualization group 2: 
- Scatter plots civil society participation vs. each single predictor - Ephrata
- Line graphs showing changes over time for each predictor vs. outcome - Ephrata
- QQ Plot - Ephrata



